# Handling Fetch Errors

Using `catch()` block for handling error.


